[tool.poetry]
name = "captcha-solver"
version = "0.1.0"
description = "Solving CAPTCHAs"
authors = ["Alexander von Renteln <alexander.vonrenteln@advantest.com>"]

[tool.poetry.dependencies]
pytesseract = "^0.3.0"
